// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace LibraryData.Models;

public partial class EbookRent
{
    public int Id { get; set; }

    public string Bookname { get; set; } = null!;

    public string IsRented { get; set; } = null!;

    public string Category { get; set; } = null!;

    public string RentAmount { get; set; } = null!;
}