// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace LibraryData.Models;

public partial class ReturnBook
{
    public int Id { get; set; }

    public string Bookname { get; set; } = null!;

    public bool IsFineApplicable { get; set; }

    public decimal FineAmount { get; set; }
}